-- Data for the followin tables goes here:
--  member
--  membre_activity
--  member_day
--  sponsor

INSERT INTO `member` VALUES ...
INSERT INTO `member_activity` VALUES ...
INSERT INTO `member_day` VALUES ...
INSERT INTO `sponsor` VALUES ...
