-- Data for the following tables goes here:
--  activity
--  activity_image
--  activity_itinerary
--  activity_tag
--  album
--  festival
--  festival_day
--  festival_event
--  festival_offer
--  location
--  notification
--  people
--  photo
--  photo_album
--  place
--  post
--  post_comment
--  post_image
--  post_tag
--  route
--  route_point
--  sponsor

INSERT INTO `activity` VALUES ...
INSERT INTO `activity_image` VALUES ...
INSERT INTO `activity_itinerary` VALUES ...
INSERT INTO `activity_tag` VALUES ...
INSERT INTO `album` VALUES ...
INSERT INTO `festival` VALUES ...
INSERT INTO `festival_day` VALUES ...
INSERT INTO `festival_event` VALUES ...
INSERT INTO `festival_offer` VALUES ...
INSERT INTO `location` VALUES ...
INSERT INTO `notification` VALUES ...
INSERT INTO `people` VALUES ...
INSERT INTO `photo` VALUES ...
INSERT INTO `photo_album` VALUES ...
INSERT INTO `place` VALUES ...
INSERT INTO `post` VALUES ...
INSERT INTO `post_comment` VALUES ...
INSERT INTO `post_image` VALUES ...
INSERT INTO `post_tag` VALUES ...
